name: stop-idiote

on:
    workflow_dispatch:

jobs:
    stopidiote:
        runs-on: ubuntu-latest

        steps:
            - name: Azure Login
              uses: Azure/login@v1
              with:
                creds: ${{ secrets.AZCREDS }}

            - name: Azure CLI script
              uses: azure/CLI@v1
              with:
                azcliversion: 2.30.0
                inlineScript: |
                    az vm stop --resource-group machinetoutebete --name idiote
                    az vm deallocate --resource-group machinetoutebete --name idiote
